import java.util.Scanner;
import java.util.Random;
public class ColorCodeGame 
{
	public static void main(String[] args) 
	{
		Scanner input = new Scanner(System.in);
		Random rand = new Random();
		ColorCodeGame game = new ColorCodeGame(); 

		int totalMoneyEntered = 0;
		int totalMoneyWon = 0;
		String playAgain = "yes";

		System.out.println("Welcome to the Color Code Guessing Game!");

		while (playAgain.equals("yes")) 
		{
			int betAmount = 0;
			while (betAmount <= 0) 
			{
				System.out.print("Enter the amount of money to bet (positive number): ");
				betAmount = input.nextInt();
				if (betAmount <= 0) 
				{
					System.out.println("Error: Amount must be positive and non-zero.");
				}//if
			}//inner while

			totalMoneyEntered += betAmount;

			String color1 = generateColor(rand);
			String color2 = generateColor(rand);
			String color3 = generateColor(rand);

			System.out.println("Colors generated by system:");
			System.out.println(color1 + " " + color2 + " " + color3);

			int winnings = matchCode(color1, color2, color3, betAmount);
			totalMoneyWon += winnings;

			if (winnings > 0) 
			{
				System.out.println("Congratulations! You won $" + winnings);
			}//if

			else
			{
				System.out.println("Sorry, you won $0");
			}//else

			input.nextLine(); 
			playAgain = "";
			while (!playAgain.equals("yes") && !playAgain.equals("no")) 
			{
				System.out.print("Do you want to play again? (yes/no): ");
				playAgain = input.nextLine().toLowerCase();
				if (!playAgain.equals("yes") && !playAgain.equals("no")) 
				{
					System.out.println("Invalid input! Please enter 'yes' or 'no'.");
				}//if
			}//inner while
		}//outer while

		System.out.println("\nGame Over!");
		System.out.println("Total money entered: $" + totalMoneyEntered);
		System.out.println("Total money won: $" + totalMoneyWon);



	}//main

	public static String generateColor(Random rand) 
	{
		String[] colors = {"Red", "Blue", "Green", "Yellow", "Purple", "Orange"};
		int index = rand.nextInt(6);
		return colors[index];
	}//generateColor

	public static int matchCode(String c1, String c2, String c3, int betAmount) 
	{
		int matchCount = 0;

		if (c1.equals(c2)) matchCount++;
		if (c1.equals(c3)) matchCount++;
		if (c2.equals(c3)) matchCount++;

		if (matchCount == 0) return 0;
		else if (matchCount == 3) return betAmount * 4;
		else return betAmount * 2;
	}//matchCode



}//class

